//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTO()
        {
            this.TBL_DETALLEPEDIDO = new HashSet<TBL_DETALLEPEDIDO>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_CODIGO { get; set; }
        public string PRO_NOMBRE { get; set; }
        public decimal PRO_PRECIOCOMPRA { get; set; }
        public decimal PRO_PRECIOVENTA { get; set; }
        public string PRO_IMAGEN { get; set; }
        public string PRO_DESCRIPCION { get; set; }
        public int PRO_STOCKMINIMO { get; set; }
        public int PRO_STOCKMAXIMO { get; set; }
        public string PRO_STATUS { get; set; }
        public System.DateTime PRO_FECHACREACION { get; set; }
        public Nullable<short> CAT_ID { get; set; }
    
        public virtual TBL_CATEGORIA TBL_CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLEPEDIDO> TBL_DETALLEPEDIDO { get; set; }
    }
}
